
#undef MP_BC_MASK_FORMAT
#define MP_BC_MASK_FORMAT (240)

#undef MP_BC_MASK_EXTRA_BYTE
#define MP_BC_MASK_EXTRA_BYTE (158)

#undef MP_BC_FORMAT_BYTE
#define MP_BC_FORMAT_BYTE (0)

#undef MP_BC_FORMAT_QSTR
#define MP_BC_FORMAT_QSTR (1)

#undef MP_BC_FORMAT_VAR_UINT
#define MP_BC_FORMAT_VAR_UINT (2)

#undef MP_BC_FORMAT_OFFSET
#define MP_BC_FORMAT_OFFSET (3)

#undef MP_BC_BASE_RESERVED
#define MP_BC_BASE_RESERVED (0)

#undef MP_BC_BASE_QSTR_O
#define MP_BC_BASE_QSTR_O (16)

#undef MP_BC_BASE_VINT_E
#define MP_BC_BASE_VINT_E (32)

#undef MP_BC_BASE_VINT_O
#define MP_BC_BASE_VINT_O (48)

#undef MP_BC_BASE_JUMP_E
#define MP_BC_BASE_JUMP_E (64)

#undef MP_BC_BASE_BYTE_O
#define MP_BC_BASE_BYTE_O (80)

#undef MP_BC_BASE_BYTE_E
#define MP_BC_BASE_BYTE_E (96)

#undef MP_BC_LOAD_CONST_SMALL_INT_MULTI
#define MP_BC_LOAD_CONST_SMALL_INT_MULTI (112)

#undef MP_BC_LOAD_FAST_MULTI
#define MP_BC_LOAD_FAST_MULTI (176)

#undef MP_BC_STORE_FAST_MULTI
#define MP_BC_STORE_FAST_MULTI (192)

#undef MP_BC_UNARY_OP_MULTI
#define MP_BC_UNARY_OP_MULTI (208)

#undef MP_BC_BINARY_OP_MULTI
#define MP_BC_BINARY_OP_MULTI (215)

#undef MP_BC_LOAD_CONST_SMALL_INT_MULTI_NUM
#define MP_BC_LOAD_CONST_SMALL_INT_MULTI_NUM (64)

#undef MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS
#define MP_BC_LOAD_CONST_SMALL_INT_MULTI_EXCESS (16)

#undef MP_BC_LOAD_FAST_MULTI_NUM
#define MP_BC_LOAD_FAST_MULTI_NUM (16)

#undef MP_BC_STORE_FAST_MULTI_NUM
#define MP_BC_STORE_FAST_MULTI_NUM (16)

#undef MP_BC_LOAD_CONST_FALSE
#define MP_BC_LOAD_CONST_FALSE (80)

#undef MP_BC_LOAD_CONST_NONE
#define MP_BC_LOAD_CONST_NONE (81)

#undef MP_BC_LOAD_CONST_TRUE
#define MP_BC_LOAD_CONST_TRUE (82)

#undef MP_BC_LOAD_CONST_SMALL_INT
#define MP_BC_LOAD_CONST_SMALL_INT (34)

#undef MP_BC_LOAD_CONST_STRING
#define MP_BC_LOAD_CONST_STRING (16)

#undef MP_BC_LOAD_CONST_OBJ
#define MP_BC_LOAD_CONST_OBJ (35)

#undef MP_BC_LOAD_NULL
#define MP_BC_LOAD_NULL (83)

#undef MP_BC_LOAD_FAST_N
#define MP_BC_LOAD_FAST_N (36)

#undef MP_BC_LOAD_DEREF
#define MP_BC_LOAD_DEREF (37)

#undef MP_BC_LOAD_NAME
#define MP_BC_LOAD_NAME (17)

#undef MP_BC_LOAD_GLOBAL
#define MP_BC_LOAD_GLOBAL (18)

#undef MP_BC_LOAD_ATTR
#define MP_BC_LOAD_ATTR (19)

#undef MP_BC_LOAD_METHOD
#define MP_BC_LOAD_METHOD (20)

#undef MP_BC_LOAD_SUPER_METHOD
#define MP_BC_LOAD_SUPER_METHOD (21)

#undef MP_BC_LOAD_BUILD_CLASS
#define MP_BC_LOAD_BUILD_CLASS (84)

#undef MP_BC_LOAD_SUBSCR
#define MP_BC_LOAD_SUBSCR (85)

#undef MP_BC_STORE_FAST_N
#define MP_BC_STORE_FAST_N (38)

#undef MP_BC_STORE_DEREF
#define MP_BC_STORE_DEREF (39)

#undef MP_BC_STORE_NAME
#define MP_BC_STORE_NAME (22)

#undef MP_BC_STORE_GLOBAL
#define MP_BC_STORE_GLOBAL (23)

#undef MP_BC_STORE_ATTR
#define MP_BC_STORE_ATTR (24)

#undef MP_BC_STORE_SUBSCR
#define MP_BC_STORE_SUBSCR (86)

#undef MP_BC_DELETE_FAST
#define MP_BC_DELETE_FAST (40)

#undef MP_BC_DELETE_DEREF
#define MP_BC_DELETE_DEREF (41)

#undef MP_BC_DELETE_NAME
#define MP_BC_DELETE_NAME (25)

#undef MP_BC_DELETE_GLOBAL
#define MP_BC_DELETE_GLOBAL (26)

#undef MP_BC_DUP_TOP
#define MP_BC_DUP_TOP (87)

#undef MP_BC_DUP_TOP_TWO
#define MP_BC_DUP_TOP_TWO (88)

#undef MP_BC_POP_TOP
#define MP_BC_POP_TOP (89)

#undef MP_BC_ROT_TWO
#define MP_BC_ROT_TWO (90)

#undef MP_BC_ROT_THREE
#define MP_BC_ROT_THREE (91)

#undef MP_BC_JUMP
#define MP_BC_JUMP (66)

#undef MP_BC_POP_JUMP_IF_TRUE
#define MP_BC_POP_JUMP_IF_TRUE (67)

#undef MP_BC_POP_JUMP_IF_FALSE
#define MP_BC_POP_JUMP_IF_FALSE (68)

#undef MP_BC_JUMP_IF_TRUE_OR_POP
#define MP_BC_JUMP_IF_TRUE_OR_POP (69)

#undef MP_BC_JUMP_IF_FALSE_OR_POP
#define MP_BC_JUMP_IF_FALSE_OR_POP (70)

#undef MP_BC_UNWIND_JUMP
#define MP_BC_UNWIND_JUMP (64)

#undef MP_BC_SETUP_WITH
#define MP_BC_SETUP_WITH (71)

#undef MP_BC_SETUP_EXCEPT
#define MP_BC_SETUP_EXCEPT (72)

#undef MP_BC_SETUP_FINALLY
#define MP_BC_SETUP_FINALLY (73)

#undef MP_BC_POP_EXCEPT_JUMP
#define MP_BC_POP_EXCEPT_JUMP (74)

#undef MP_BC_FOR_ITER
#define MP_BC_FOR_ITER (75)

#undef MP_BC_WITH_CLEANUP
#define MP_BC_WITH_CLEANUP (92)

#undef MP_BC_END_FINALLY
#define MP_BC_END_FINALLY (93)

#undef MP_BC_GET_ITER
#define MP_BC_GET_ITER (94)

#undef MP_BC_GET_ITER_STACK
#define MP_BC_GET_ITER_STACK (95)

#undef MP_BC_BUILD_TUPLE
#define MP_BC_BUILD_TUPLE (42)

#undef MP_BC_BUILD_LIST
#define MP_BC_BUILD_LIST (43)

#undef MP_BC_BUILD_MAP
#define MP_BC_BUILD_MAP (44)

#undef MP_BC_STORE_MAP
#define MP_BC_STORE_MAP (98)

#undef MP_BC_BUILD_SET
#define MP_BC_BUILD_SET (45)

#undef MP_BC_BUILD_SLICE
#define MP_BC_BUILD_SLICE (46)

#undef MP_BC_STORE_COMP
#define MP_BC_STORE_COMP (47)

#undef MP_BC_UNPACK_SEQUENCE
#define MP_BC_UNPACK_SEQUENCE (48)

#undef MP_BC_UNPACK_EX
#define MP_BC_UNPACK_EX (49)

#undef MP_BC_RETURN_VALUE
#define MP_BC_RETURN_VALUE (99)

#undef MP_BC_RAISE_LAST
#define MP_BC_RAISE_LAST (100)

#undef MP_BC_RAISE_OBJ
#define MP_BC_RAISE_OBJ (101)

#undef MP_BC_RAISE_FROM
#define MP_BC_RAISE_FROM (102)

#undef MP_BC_YIELD_VALUE
#define MP_BC_YIELD_VALUE (103)

#undef MP_BC_YIELD_FROM
#define MP_BC_YIELD_FROM (104)

#undef MP_BC_MAKE_FUNCTION
#define MP_BC_MAKE_FUNCTION (50)

#undef MP_BC_MAKE_FUNCTION_DEFARGS
#define MP_BC_MAKE_FUNCTION_DEFARGS (51)

#undef MP_BC_MAKE_CLOSURE
#define MP_BC_MAKE_CLOSURE (32)

#undef MP_BC_MAKE_CLOSURE_DEFARGS
#define MP_BC_MAKE_CLOSURE_DEFARGS (33)

#undef MP_BC_CALL_FUNCTION
#define MP_BC_CALL_FUNCTION (52)

#undef MP_BC_CALL_FUNCTION_VAR_KW
#define MP_BC_CALL_FUNCTION_VAR_KW (53)

#undef MP_BC_CALL_METHOD
#define MP_BC_CALL_METHOD (54)

#undef MP_BC_CALL_METHOD_VAR_KW
#define MP_BC_CALL_METHOD_VAR_KW (55)

#undef MP_BC_IMPORT_NAME
#define MP_BC_IMPORT_NAME (27)

#undef MP_BC_IMPORT_FROM
#define MP_BC_IMPORT_FROM (28)

#undef MP_BC_IMPORT_STAR
#define MP_BC_IMPORT_STAR (105)
